### ISSUE TITLE
The slides do not show in Microsoft Edge

### ISSUE THREAD

**Issue by celestialphineas** [thetype/10#1]
I‘m just here to remind you that the page does not fully support Windows Edge. Images in the slides are loaded, but the element is not shown. Please check out `app.js` and test the page on Microsoft Edge.

P.S. The page works fine on Internet Explorer 11 though. Possibly it is due to a bug of Microsoft Edge, for it is designed to have the same behavior as Chromium.

You are doing a great work! Thank you. (＾∪＾)ノ

**Comment by realfish** [comment]
Thanks you for the first issue!

For lack of a PC with Win 10, I tested and located this bug via [a remote MS Edge](https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/). (Hope it could meet the need.)

I believe that [`.slideshow { display: flex; }`](https://github.com/thetype/10/blob/v1.0.0/src/less/module/slideshow-new.less#L3) causes the height collapse. It seems that Edge's flexbox behaves same with Gecko (in which this bug is also reproduced), but different with Blink/WebKit. Will fix it in the next release.

This project may be buggy as it's under the pre-release stage at present. Any feedback is welcome.

**Comment by realfish** [comment]
Fixed in [v1.1.0](https://github.com/thetype/10/blob/v1.1.0/CHANGELOG.md#version-110-2017-06-17).

**Comment by celestialphineas** [comment]
Now it works fine. Many thanks.

(●'◡'●) And I just received the TIB postcard I bought. Happy~
